CREATE TABLE IF NOT EXISTS `inbox_tickets` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `tenantId` int NULL,
  `threadId` varchar(128) NOT NULL,
  `subject` varchar(1000) NULL,
  `requesterEmail` varchar(320) NULL,
  `requesterName` varchar(255) NULL,
  `receivedByAddress` varchar(320) NULL,
  `channel` enum('email','phone','web','portal','manual') NOT NULL DEFAULT 'email',
  `priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  `status` enum('new','open','waiting_customer','customer_replied','closed','spam') NOT NULL DEFAULT 'new',
  `assignedToId` int NULL,
  `assignedToName` varchar(100) NULL,
  `assignedAt` timestamp NULL DEFAULT NULL,
  `matchedJobId` int NULL,
  `matchedLeadId` int NULL,
  `matchedClientEmail` varchar(320) NULL,
  `firstMessageId` int NULL,
  `latestMessageId` int NULL,
  `latestDirection` enum('inbound','outbound') NULL,
  `messageCount` int NOT NULL DEFAULT 0,
  `unreadCount` int NOT NULL DEFAULT 0,
  `isStarred` tinyint(1) NOT NULL DEFAULT 0,
  `lastInboundAt` timestamp NULL DEFAULT NULL,
  `lastOutboundAt` timestamp NULL DEFAULT NULL,
  `lastMessageAt` timestamp NULL DEFAULT NULL,
  `slaWarningAt` timestamp NULL DEFAULT NULL,
  `slaDueAt` timestamp NULL DEFAULT NULL,
  `slaBreachedAt` timestamp NULL DEFAULT NULL,
  `resolvedAt` timestamp NULL DEFAULT NULL,
  `resolvedBy` int NULL,
  `resolvedByName` varchar(100) NULL,
  `resolutionNotes` text NULL,
  `closedReason` varchar(100) NULL,
  `createdBy` int NULL,
  `createdByName` varchar(100) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE `inbox_tickets`
  ADD COLUMN IF NOT EXISTS `tenantId` int NULL,
  ADD COLUMN IF NOT EXISTS `threadId` varchar(128) NULL,
  ADD COLUMN IF NOT EXISTS `subject` varchar(1000) NULL,
  ADD COLUMN IF NOT EXISTS `requesterEmail` varchar(320) NULL,
  ADD COLUMN IF NOT EXISTS `requesterName` varchar(255) NULL,
  ADD COLUMN IF NOT EXISTS `receivedByAddress` varchar(320) NULL,
  ADD COLUMN IF NOT EXISTS `channel` enum('email','phone','web','portal','manual') NOT NULL DEFAULT 'email',
  ADD COLUMN IF NOT EXISTS `priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS `status` enum('new','open','waiting_customer','customer_replied','closed','spam') NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS `assignedToId` int NULL,
  ADD COLUMN IF NOT EXISTS `assignedToName` varchar(100) NULL,
  ADD COLUMN IF NOT EXISTS `assignedAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `matchedJobId` int NULL,
  ADD COLUMN IF NOT EXISTS `matchedLeadId` int NULL,
  ADD COLUMN IF NOT EXISTS `matchedClientEmail` varchar(320) NULL,
  ADD COLUMN IF NOT EXISTS `firstMessageId` int NULL,
  ADD COLUMN IF NOT EXISTS `latestMessageId` int NULL,
  ADD COLUMN IF NOT EXISTS `latestDirection` enum('inbound','outbound') NULL,
  ADD COLUMN IF NOT EXISTS `messageCount` int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `unreadCount` int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `isStarred` tinyint(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `lastInboundAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `lastOutboundAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `lastMessageAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `slaWarningAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `slaDueAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `slaBreachedAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `resolvedAt` timestamp NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `resolvedBy` int NULL,
  ADD COLUMN IF NOT EXISTS `resolvedByName` varchar(100) NULL,
  ADD COLUMN IF NOT EXISTS `resolutionNotes` text NULL,
  ADD COLUMN IF NOT EXISTS `closedReason` varchar(100) NULL,
  ADD COLUMN IF NOT EXISTS `createdBy` int NULL,
  ADD COLUMN IF NOT EXISTS `createdByName` varchar(100) NULL,
  ADD COLUMN IF NOT EXISTS `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS `inbox_ticket_tags` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `ticketId` int NOT NULL,
  `tagId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
