CREATE TABLE IF NOT EXISTS `saas_billing_plans` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `code` varchar(80) NOT NULL,
  `name` varchar(160) NOT NULL,
  `description` text NULL,
  `status` enum('draft','active','archived') NOT NULL DEFAULT 'draft',
  `billingModel` enum('flat','seat','usage','hybrid','manual') NOT NULL DEFAULT 'hybrid',
  `interval` enum('month','year','custom') NOT NULL DEFAULT 'month',
  `basePriceCents` int NOT NULL DEFAULT 0,
  `includedSeats` int NOT NULL DEFAULT 0,
  `includedUsage` json NULL,
  `overageRates` json NULL,
  `modules` json NULL,
  `limits` json NULL,
  `metadata` json NULL,
  `stripeProductId` varchar(255) NULL,
  `stripePriceId` varchar(255) NULL,
  `createdBy` int NULL,
  `createdByName` varchar(255) NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_saas_billing_plans_code` (`code`),
  KEY `idx_saas_billing_plans_status` (`status`),
  KEY `idx_saas_billing_plans_model` (`billingModel`),
  CONSTRAINT `fk_saas_billing_plans_created_by` FOREIGN KEY (`createdBy`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `saas_tenant_billing_accounts` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `tenantId` int NOT NULL,
  `legalName` varchar(255) NULL,
  `billingEmail` varchar(320) NULL,
  `billingOwnerUserId` int NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'AUD',
  `taxId` varchar(80) NULL,
  `paymentProvider` enum('stripe','xero','manual') NOT NULL DEFAULT 'manual',
  `providerCustomerId` varchar(255) NULL,
  `status` enum('trialing','active','past_due','suspended','cancelled','manual') NOT NULL DEFAULT 'manual',
  `trialEndsAt` timestamp NULL DEFAULT NULL,
  `nextInvoiceAt` timestamp NULL DEFAULT NULL,
  `reconcileStatus` enum('unknown','ok','attention','failed') NOT NULL DEFAULT 'unknown',
  `reconcileNotes` text NULL,
  `lastSyncedAt` timestamp NULL DEFAULT NULL,
  `notes` text NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_saas_tenant_billing_account_tenant` (`tenantId`),
  KEY `idx_saas_tenant_billing_accounts_status` (`status`),
  KEY `idx_saas_tenant_billing_accounts_reconcile` (`reconcileStatus`),
  KEY `idx_saas_tenant_billing_accounts_provider_customer` (`providerCustomerId`),
  CONSTRAINT `fk_saas_tenant_billing_accounts_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_saas_tenant_billing_accounts_owner` FOREIGN KEY (`billingOwnerUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `saas_billing_subscriptions` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `tenantId` int NOT NULL,
  `billingAccountId` int NULL,
  `planId` int NULL,
  `status` enum('trialing','active','paused','past_due','cancelled','expired') NOT NULL DEFAULT 'trialing',
  `seatQuantity` int NOT NULL DEFAULT 0,
  `usageQuantity` int NOT NULL DEFAULT 0,
  `billingModelOverride` enum('flat','seat','usage','hybrid','manual') NULL,
  `unitAmountCents` int NULL,
  `mrrCents` int NOT NULL DEFAULT 0,
  `provider` enum('stripe','xero','manual') NOT NULL DEFAULT 'manual',
  `providerSubscriptionId` varchar(255) NULL,
  `providerPriceId` varchar(255) NULL,
  `providerStatus` varchar(80) NULL,
  `currentPeriodStart` timestamp NULL DEFAULT NULL,
  `currentPeriodEnd` timestamp NULL DEFAULT NULL,
  `cancelAtPeriodEnd` tinyint(1) NOT NULL DEFAULT 0,
  `cancelledAt` timestamp NULL DEFAULT NULL,
  `metadata` json NULL,
  `reconcileStatus` enum('unknown','ok','attention','failed') NOT NULL DEFAULT 'unknown',
  `reconcileNotes` text NULL,
  `lastSyncedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_saas_billing_subscriptions_tenant` (`tenantId`),
  KEY `idx_saas_billing_subscriptions_tenant_status` (`tenantId`, `status`),
  KEY `idx_saas_billing_subscriptions_plan` (`planId`),
  KEY `idx_saas_billing_subscriptions_provider_sub` (`providerSubscriptionId`),
  CONSTRAINT `fk_saas_billing_subscriptions_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_saas_billing_subscriptions_account` FOREIGN KEY (`billingAccountId`) REFERENCES `saas_tenant_billing_accounts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_saas_billing_subscriptions_plan` FOREIGN KEY (`planId`) REFERENCES `saas_billing_plans` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `saas_billing_events` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `tenantId` int NULL,
  `billingAccountId` int NULL,
  `subscriptionId` int NULL,
  `provider` enum('stripe','xero','manual','system') NOT NULL DEFAULT 'system',
  `providerEventId` varchar(255) NULL,
  `eventType` varchar(120) NOT NULL,
  `status` enum('received','processed','failed','ignored') NOT NULL DEFAULT 'received',
  `severity` enum('info','warning','critical') NOT NULL DEFAULT 'info',
  `payload` json NULL,
  `errorMessage` text NULL,
  `retryCount` int NOT NULL DEFAULT 0,
  `receivedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_saas_billing_events_provider_event` (`provider`, `providerEventId`),
  KEY `idx_saas_billing_events_tenant` (`tenantId`),
  KEY `idx_saas_billing_events_status` (`status`),
  KEY `idx_saas_billing_events_received` (`receivedAt`),
  CONSTRAINT `fk_saas_billing_events_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_saas_billing_events_account` FOREIGN KEY (`billingAccountId`) REFERENCES `saas_tenant_billing_accounts` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_saas_billing_events_subscription` FOREIGN KEY (`subscriptionId`) REFERENCES `saas_billing_subscriptions` (`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `saas_admin_audit_log` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `tenantId` int NULL,
  `actorUserId` int NULL,
  `actorUserName` varchar(255) NULL,
  `action` varchar(120) NOT NULL,
  `entityType` varchar(80) NOT NULL,
  `entityId` varchar(80) NULL,
  `beforeJson` json NULL,
  `afterJson` json NULL,
  `metadata` json NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_saas_admin_audit_tenant` (`tenantId`),
  KEY `idx_saas_admin_audit_actor` (`actorUserId`),
  KEY `idx_saas_admin_audit_entity` (`entityType`, `entityId`),
  KEY `idx_saas_admin_audit_created` (`createdAt`),
  CONSTRAINT `fk_saas_admin_audit_tenant` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_saas_admin_audit_actor` FOREIGN KEY (`actorUserId`) REFERENCES `users` (`id`) ON DELETE SET NULL
);
