CREATE TABLE IF NOT EXISTS `proposal_library_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenantId` INT NOT NULL,
  `sectionType` VARCHAR(50) NOT NULL DEFAULT 'all',
  `contentType` VARCHAR(50) NOT NULL DEFAULT 'overview',
  `title` VARCHAR(255) NOT NULL,
  `body` MEDIUMTEXT NULL,
  `imageUrl` TEXT NULL,
  `imageAlt` VARCHAR(255) NULL,
  `originalFileName` VARCHAR(255) NULL,
  `originalImageWidth` INT NULL,
  `originalImageHeight` INT NULL,
  `imageWidth` INT NULL,
  `imageHeight` INT NULL,
  `imageSizeBytes` INT NULL,
  `imageMimeType` VARCHAR(80) NULL,
  `imageWarning` TEXT NULL,
  `defaultIncluded` BOOLEAN NOT NULL DEFAULT TRUE,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `sortOrder` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_proposal_library_tenant` (`tenantId`),
  KEY `idx_proposal_library_tenant_section` (`tenantId`, `sectionType`, `isActive`),
  KEY `idx_proposal_library_tenant_default` (`tenantId`, `defaultIncluded`, `isActive`),
  CONSTRAINT `fk_proposal_library_tenant`
    FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`) ON DELETE CASCADE
);
